// AUTO-GENERATED by scripts/generate-metro-extra.mjs from Delhi_Metro_Complete_303.csv — do not edit by hand.
export type StationExtra = {
  opened: string | null;
  layout: string | null;
  platformType: string | null;
  interchangeLines: string[];
  notes: string[];
  distFromLineStartKm: number[];
};

export const STATION_EXTRA: Record<string, StationExtra> = {
  "SHT": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: New Bus Adda"
    ],
    "distFromLineStartKm": [
      0
    ]
  },
  "HNR": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.5
    ]
  },
  "ARL": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      2.5
    ]
  },
  "MHN": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.5
    ]
  },
  "SYP": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      4.5
    ]
  },
  "MMS": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Rajendra Nagar"
    ],
    "distFromLineStartKm": [
      5.7
    ]
  },
  "RJB": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.9
    ]
  },
  "SNG": {
    "opened": "08-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      8.2
    ]
  },
  "DSG": {
    "opened": "04-06-2008",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      9.4
    ]
  },
  "JHM": {
    "opened": "04-06-2008",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.3
    ]
  },
  "MSP": {
    "opened": "04-06-2008",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      11.4
    ]
  },
  "SHD": {
    "opened": "24-12-2002",
    "layout": "At-Grade",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Delhi Shahdara Junction Railway"
    ],
    "distFromLineStartKm": [
      12.5
    ]
  },
  "WLC": {
    "opened": "25-12-2002",
    "layout": "At-Grade",
    "platformType": "Island",
    "interchangeLines": [
      "Pink Line",
      "Red Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      13.7,
      46
    ]
  },
  "SLM": {
    "opened": "24-12-2002",
    "layout": "At-Grade",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      14.8
    ]
  },
  "SHP": {
    "opened": "24-12-2002",
    "layout": "At-Grade",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      16.4
    ]
  },
  "KSG": {
    "opened": "24-12-2002",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Yellow Line",
      "Violet Line",
      "Red Line"
    ],
    "notes": [
      "Transfer: Kashmere Gate ISBT"
    ],
    "distFromLineStartKm": [
      18.5,
      13.2,
      0
    ]
  },
  "THS": {
    "opened": "24-12-2002",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      19.7
    ]
  },
  "PLB": {
    "opened": "03-10-2003",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      20.6
    ]
  },
  "PRT": {
    "opened": "03-10-2003",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Subzi Mandi Railway Station"
    ],
    "distFromLineStartKm": [
      21.4
    ]
  },
  "SHN": {
    "opened": "03-10-2003",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Delhi Sarai Rohilla Railway"
    ],
    "distFromLineStartKm": [
      23.1
    ]
  },
  "IND": {
    "opened": "03-10-2003",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Green Line",
      "Red Line"
    ],
    "notes": [
      "Former: Trinagar"
    ],
    "distFromLineStartKm": [
      24.3,
      0
    ]
  },
  "KNY": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      25.5
    ]
  },
  "KPR": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      26.2
    ]
  },
  "PPR": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Magenta Line (Phase4)",
      "Red Line"
    ],
    "notes": [
      "Former: Pitampura",
      "Former: Pitampura; renamed"
    ],
    "distFromLineStartKm": [
      27,
      1.2
    ]
  },
  "NSP": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Red Line"
    ],
    "notes": [
      "Former: Wazirpur"
    ],
    "distFromLineStartKm": [
      27.8,
      5.1
    ]
  },
  "KTE": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      28.6
    ]
  },
  "RHE": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      30.4
    ]
  },
  "RHW": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      31.7
    ]
  },
  "RTH": {
    "opened": "31-03-2004",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      32.7
    ]
  },
  "SBD": {
    "opened": "10-11-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      0
    ]
  },
  "RSN": {
    "opened": "10-11-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      0.8
    ]
  },
  "HBM": {
    "opened": "10-11-2015",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [
      "Magenta Line (Phase4)",
      "Yellow Line"
    ],
    "notes": [
      "Former: Badli Mor"
    ],
    "distFromLineStartKm": [
      2.1,
      6.5
    ]
  },
  "JHP": {
    "opened": "04-02-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.4
    ]
  },
  "ANP": {
    "opened": "04-02-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      4.7
    ]
  },
  "AZP": {
    "opened": "04-02-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Yellow Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      6.2,
      2.1
    ]
  },
  "MDT": {
    "opened": "04-02-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.6
    ]
  },
  "GTB": {
    "opened": "04-02-2009",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: GTB Nagar"
    ],
    "distFromLineStartKm": [
      9
    ]
  },
  "VVD": {
    "opened": "20-12-2004",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      9.8
    ]
  },
  "VHS": {
    "opened": "20-12-2004",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.8
    ]
  },
  "CVL": {
    "opened": "20-12-2004",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12.1
    ]
  },
  "CCW": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Delhi Main. Transfer: Delhi Junction Railway"
    ],
    "distFromLineStartKm": [
      14.3
    ]
  },
  "CWB": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Second deepest station"
    ],
    "distFromLineStartKm": [
      15.3
    ]
  },
  "NDL": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [
      "Airport Express (Orange)",
      "Yellow Line"
    ],
    "notes": [
      "Transfer: New Delhi Railway Station",
      "Transfer: New Delhi Railway Station. Check-in facilities"
    ],
    "distFromLineStartKm": [
      16.1,
      0
    ]
  },
  "RJC": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [
      "Blue Line",
      "Yellow Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      17.2,
      30.1
    ]
  },
  "PCK": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.5
    ]
  },
  "CSS": {
    "opened": "03-07-2005",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [
      "Violet Line",
      "Yellow Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      19.4,
      8.5
    ]
  },
  "UDB": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Udyog Bhawan"
    ],
    "distFromLineStartKm": [
      19.7
    ]
  },
  "LKM": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Race Course"
    ],
    "distFromLineStartKm": [
      21.3
    ]
  },
  "JRB": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      22.5
    ]
  },
  "INA": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [
      "Pink Line",
      "Yellow Line"
    ],
    "notes": [
      "Former: INA"
    ],
    "distFromLineStartKm": [
      23.8,
      24.9
    ]
  },
  "AIM": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      24.6
    ]
  },
  "GRP": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      25.6
    ]
  },
  "HKS": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [
      "Magenta Line",
      "Yellow Line"
    ],
    "notes": [
      "Deepest station in Delhi (29m)",
      "Deepest station in Delhi"
    ],
    "distFromLineStartKm": [
      27.4,
      20.3
    ]
  },
  "MLN": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      29.1
    ]
  },
  "SKT": {
    "opened": "03-09-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      30
    ]
  },
  "QMN": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      31.7
    ]
  },
  "CHT": {
    "opened": "26-08-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      33
    ]
  },
  "SLT": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      34.6
    ]
  },
  "GHT": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      35.9
    ]
  },
  "AGH": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      38.6
    ]
  },
  "GDN": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Garden Estate"
    ],
    "distFromLineStartKm": [
      40.9
    ]
  },
  "SKP": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Rapid Metro Gurgaon",
      "Yellow Line"
    ],
    "notes": [
      "Transfer via walkway",
      "Transfer to Yellow Line via walkway"
    ],
    "distFromLineStartKm": [
      41.9,
      0
    ]
  },
  "MGR": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      43.1
    ]
  },
  "IFC": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      44.2
    ]
  },
  "HCC": {
    "opened": "21-06-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: HUDA City Centre"
    ],
    "distFromLineStartKm": [
      45.7
    ]
  },
  "D21": {
    "opened": "30-10-2010",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [
      "Airport Express (Orange)",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      0,
      20.8
    ]
  },
  "DS8": {
    "opened": "30-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.7
    ]
  },
  "DS9": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      2.7
    ]
  },
  "DS10": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.8
    ]
  },
  "DS11": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      4.8
    ]
  },
  "DS12": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5.8
    ]
  },
  "DS13": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.7
    ]
  },
  "DS14": {
    "opened": "01-04-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.6
    ]
  },
  "DWK": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Grey Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      9.1,
      0
    ]
  },
  "DMR": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.2
    ]
  },
  "NWD": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      11.4
    ]
  },
  "UNW": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12.4
    ]
  },
  "UNE": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      13.4
    ]
  },
  "JPW": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [
      "Magenta Line",
      "Blue Line"
    ],
    "notes": [
      "India's tallest escalator at this interchange",
      "India's tallest escalator here"
    ],
    "distFromLineStartKm": [
      14.7,
      2.8
    ]
  },
  "JPE": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      15.7
    ]
  },
  "TLK": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      16.7
    ]
  },
  "SBN": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      17.6
    ]
  },
  "TGD": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.5
    ]
  },
  "RJG": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      19.6,
      11.3
    ]
  },
  "RMN": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      20.6
    ]
  },
  "MTN": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      21.8
    ]
  },
  "KTN": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [
      "Green Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      22.8,
      2.1
    ]
  },
  "SDP": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      23.5
    ]
  },
  "PTG": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      24.8
    ]
  },
  "RDP": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      25.7
    ]
  },
  "KRB": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      26.7
    ]
  },
  "JND": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      27.9
    ]
  },
  "RAK": {
    "opened": "30-12-2005",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      28.9
    ]
  },
  "BRK": {
    "opened": "30-12-2005",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Shivaji Bridge Railway Station"
    ],
    "distFromLineStartKm": [
      30.8
    ]
  },
  "MDH": {
    "opened": "11-11-2006",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [
      "Violet Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      31.8,
      5.8
    ]
  },
  "PGM": {
    "opened": "11-11-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Pragati Maidan. Delhi Metro Museum inside"
    ],
    "distFromLineStartKm": [
      32.6
    ]
  },
  "IDP": {
    "opened": "11-11-2006",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      33.4
    ]
  },
  "YMB": {
    "opened": "10-05-2009",
    "layout": "At-Grade",
    "platformType": "Island",
    "interchangeLines": [
      "Blue Line Branch",
      "Blue Line"
    ],
    "notes": [
      "Branch diverges here",
      "Branch from Blue Line main"
    ],
    "distFromLineStartKm": [
      35.2,
      0
    ]
  },
  "AKD": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      36.5
    ]
  },
  "MPH": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [
      "Pink Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      38.3,
      35.8
    ]
  },
  "MPE": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      39.5
    ]
  },
  "NAN": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Delhi-Meerut RRTS"
    ],
    "distFromLineStartKm": [
      40.4
    ]
  },
  "N15": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      41.4
    ]
  },
  "N16": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      42.5
    ]
  },
  "N18": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      43.6
    ]
  },
  "BOT": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Magenta Line",
      "Blue Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      44.7,
      35.8
    ]
  },
  "GCN": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      45.9
    ]
  },
  "NCC": {
    "opened": "12-11-2009",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      47.2
    ]
  },
  "N34": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      48.5
    ]
  },
  "N52": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Aqua Line (Noida Metro)"
    ],
    "notes": [
      "Transfer to Aqua Line"
    ],
    "distFromLineStartKm": [
      50
    ]
  },
  "N61": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      51.2
    ]
  },
  "N59": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      52.2
    ]
  },
  "N62": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      53.1
    ]
  },
  "NEC": {
    "opened": "09-03-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      54.5
    ]
  },
  "LXN": {
    "opened": "06-01-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.3
    ]
  },
  "NVH": {
    "opened": "06-01-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      2.4
    ]
  },
  "PVH": {
    "opened": "06-01-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.4
    ]
  },
  "KKD": {
    "opened": "06-01-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Blue Line Branch"
    ],
    "notes": [],
    "distFromLineStartKm": [
      4.6,
      42.1
    ]
  },
  "AVH": {
    "opened": "06-01-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Blue Line Branch"
    ],
    "notes": [
      "Transfer: Anand Vihar Railway Terminal; Anand Vihar ISBT",
      "Transfer: Anand Vihar Railway Terminal; ISBT"
    ],
    "distFromLineStartKm": [
      5.7,
      41.1
    ]
  },
  "KSM": {
    "opened": "14-07-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.5
    ]
  },
  "VAI": {
    "opened": "14-07-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      8.1
    ]
  },
  "APM": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Green Line Branch",
      "Green Line"
    ],
    "notes": [
      "Branch diverges here"
    ],
    "distFromLineStartKm": [
      1.4,
      0
    ]
  },
  "SRS": {
    "opened": "27-08-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Patel Nagar Railway Station"
    ],
    "distFromLineStartKm": [
      1.1
    ]
  },
  "PBE": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Punjabi Bagh East"
    ],
    "distFromLineStartKm": [
      2.3
    ]
  },
  "PBW": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line",
      "Green Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      3.2,
      7.7
    ]
  },
  "SJP": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.9
    ]
  },
  "MDP": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5
    ]
  },
  "PVE": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5.7
    ]
  },
  "PVW": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.7
    ]
  },
  "PGA": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.6
    ]
  },
  "UNR": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      8.8
    ]
  },
  "MSS": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Surajmal Stadium"
    ],
    "distFromLineStartKm": [
      9.5
    ]
  },
  "NGL": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.3
    ]
  },
  "NRS": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Transfer: Nangloi Railway Station"
    ],
    "distFromLineStartKm": [
      11.2
    ]
  },
  "RPK": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12.4
    ]
  },
  "MDK": {
    "opened": "02-04-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      13.7
    ]
  },
  "MIA": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      15
    ]
  },
  "GHV": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      17.1
    ]
  },
  "TKK": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.9
    ]
  },
  "TKB": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      20.2
    ]
  },
  "PSR": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Modern Industrial Estate"
    ],
    "distFromLineStartKm": [
      21.5
    ]
  },
  "BHG": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Bus Stand"
    ],
    "distFromLineStartKm": [
      23
    ]
  },
  "BHS": {
    "opened": "24-06-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: City Park"
    ],
    "distFromLineStartKm": [
      24.8
    ]
  },
  "LAL": {
    "opened": "28-05-2017",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Red Fort"
    ],
    "distFromLineStartKm": [
      1.5
    ]
  },
  "JMS": {
    "opened": "28-05-2017",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      2.3
    ]
  },
  "DLG": {
    "opened": "28-05-2017",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.7
    ]
  },
  "ITO": {
    "opened": "08-06-2015",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5
    ]
  },
  "JNP": {
    "opened": "26-06-2014",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.2
    ]
  },
  "KMK": {
    "opened": "03-10-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.6
    ]
  },
  "JLN": {
    "opened": "03-10-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12
    ]
  },
  "JPG": {
    "opened": "03-10-2010",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Lodi Colony"
    ],
    "distFromLineStartKm": [
      12.9
    ]
  },
  "LJN": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [
      "Pink Line",
      "Violet Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      14.4,
      27.7
    ]
  },
  "MLC": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      15.1
    ]
  },
  "KLC": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      16.4
    ]
  },
  "NHP": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      17.4
    ]
  },
  "KKM": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Magenta Line",
      "Violet Line"
    ],
    "notes": [],
    "distFromLineStartKm": [
      18.2,
      25.7
    ]
  },
  "GPR": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.9
    ]
  },
  "HNO": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Okhla"
    ],
    "distFromLineStartKm": [
      20
    ]
  },
  "JAP": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Jasola"
    ],
    "distFromLineStartKm": [
      20.9
    ]
  },
  "SNV": {
    "opened": "03-10-2010",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      22.1
    ]
  },
  "MOH": {
    "opened": "14-01-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      23.3
    ]
  },
  "TGV": {
    "opened": "14-01-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Tughlakabad"
    ],
    "distFromLineStartKm": [
      25.2
    ]
  },
  "BDB": {
    "opened": "14-01-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Badarpur"
    ],
    "distFromLineStartKm": [
      26.3
    ]
  },
  "SRN": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      28
    ]
  },
  "NPC": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      30.4
    ]
  },
  "MMP": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      32.3
    ]
  },
  "S28": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      33.9
    ]
  },
  "BKM": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      35
    ]
  },
  "OFD": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      36.8
    ]
  },
  "NCA": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Ajronda"
    ],
    "distFromLineStartKm": [
      38.2
    ]
  },
  "BAK": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      39.5
    ]
  },
  "ESM": {
    "opened": "06-09-2015",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: YMCA Chowk"
    ],
    "distFromLineStartKm": [
      40.5
    ]
  },
  "SIS": {
    "opened": "19-11-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: NCB/Goodyear Chowk"
    ],
    "distFromLineStartKm": [
      42.5
    ]
  },
  "RNS": {
    "opened": "19-11-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Ballabhgarh"
    ],
    "distFromLineStartKm": [
      44.1
    ]
  },
  "MJP": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Magenta Line (Phase4)",
      "Pink Line"
    ],
    "notes": [
      "Former: Mukundpur",
      "Phase 4 terminus / Pink Line interchange"
    ],
    "distFromLineStartKm": [
      0,
      9.9
    ]
  },
  "SHB": {
    "opened": "14-03-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.7
    ]
  },
  "SHK": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.3
    ]
  },
  "ESI": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: ESI Hospital"
    ],
    "distFromLineStartKm": [
      10.2
    ]
  },
  "MYP": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12.8
    ]
  },
  "NRV": {
    "opened": "14-03-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      14.3
    ]
  },
  "DCT": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      16.1
    ]
  },
  "DGD": {
    "opened": "14-03-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Airport Express (Orange)"
    ],
    "notes": [
      "For Delhi University South Campus"
    ],
    "distFromLineStartKm": [
      19.7
    ]
  },
  "SMV": {
    "opened": "06-08-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      21
    ]
  },
  "BCP": {
    "opened": "06-08-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      22.6
    ]
  },
  "SJN": {
    "opened": "06-08-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      23.8
    ]
  },
  "SEX": {
    "opened": "06-08-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      26.1
    ]
  },
  "VBP": {
    "opened": "31-12-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      29.1
    ]
  },
  "ASH": {
    "opened": "31-12-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      30.3
    ]
  },
  "HNZ": {
    "opened": "31-12-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Transfer: Hazrat Nizamuddin Railway; Sarai Kale Khan ISBT"
    ],
    "distFromLineStartKm": [
      32.2
    ]
  },
  "MPK": {
    "opened": "31-12-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Mayur Vihar Pocket I"
    ],
    "distFromLineStartKm": [
      35
    ]
  },
  "TSL": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Trilokpuri"
    ],
    "distFromLineStartKm": [
      37.1
    ]
  },
  "VNE": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: East Vinod Nagar"
    ],
    "distFromLineStartKm": [
      37.9
    ]
  },
  "MWV": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Vinod Nagar West"
    ],
    "distFromLineStartKm": [
      38.5
    ]
  },
  "IPX": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      39.5
    ]
  },
  "KRC": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      43.2
    ]
  },
  "KRN": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      43.9
    ]
  },
  "EAN": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      44.9
    ]
  },
  "JFB": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      47.2
    ]
  },
  "MJR": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Branch terminal for Shiv Vihar direction"
    ],
    "distFromLineStartKm": [
      48.3
    ]
  },
  "GKP": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      49.6
    ]
  },
  "JRP": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      50.9
    ]
  },
  "SVH": {
    "opened": "31-10-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      51.8
    ]
  },
  "BJP": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Ring section"
    ],
    "distFromLineStartKm": [
      53
    ]
  },
  "YVH": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      54.3
    ]
  },
  "KJK": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      56
    ]
  },
  "NSV": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      57.5
    ]
  },
  "JGW": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      59.3
    ]
  },
  "JHD": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      60.4
    ]
  },
  "BUR": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      61.2
    ]
  },
  "KPE": {
    "opened": "05-01-2025",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Phase 4 terminus"
    ],
    "distFromLineStartKm": [
      0
    ]
  },
  "DBM": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: Dabri Mor"
    ],
    "distFromLineStartKm": [
      4.8
    ]
  },
  "DSP": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5.9
    ]
  },
  "PAL": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.4
    ]
  },
  "SBT": {
    "opened": "29-05-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10
    ]
  },
  "IGI": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Connects to IGI Terminal 1"
    ],
    "distFromLineStartKm": [
      11.7
    ]
  },
  "SKV": {
    "opened": "29-05-2018",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Defense area station"
    ],
    "distFromLineStartKm": [
      13.5
    ]
  },
  "VSV": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      15.6
    ]
  },
  "MNK": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      16.8
    ]
  },
  "RKP": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.2
    ]
  },
  "IIT": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "For IIT Delhi"
    ],
    "distFromLineStartKm": [
      19.1
    ]
  },
  "PSP": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      21.8
    ]
  },
  "CHD": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      22.7
    ]
  },
  "GK1": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      23.6
    ]
  },
  "NEN": {
    "opened": "29-05-2018",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      24.9
    ]
  },
  "ONS": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      26.5
    ]
  },
  "SKW": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      27.6
    ]
  },
  "JMI": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      28.8
    ]
  },
  "OVH": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      29.3
    ]
  },
  "JSB": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      31.1
    ]
  },
  "KLK": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      32.5
    ]
  },
  "OBS": {
    "opened": "25-12-2017",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      34.1
    ]
  },
  "DPC": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Phase 4 new section start"
    ],
    "distFromLineStartKm": [
      0
    ]
  },
  "UPV": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: Prashant Vihar"
    ],
    "distFromLineStartKm": [
      2.5
    ]
  },
  "HPV": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Former: North Pitampura"
    ],
    "distFromLineStartKm": [
      3.8
    ]
  },
  "BLW": {
    "opened": "08-03-2026",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5.2
    ]
  },
  "NS51": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Blue Line"
    ],
    "notes": [
      "Transfer to Delhi Metro Blue Line"
    ],
    "distFromLineStartKm": [
      0
    ]
  },
  "NS50": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.3
    ]
  },
  "NS76": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      2.3
    ]
  },
  "NS101": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.4
    ]
  },
  "NS81": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      4.3
    ]
  },
  "NSZ": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      6.3
    ]
  },
  "NS83": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      7.4
    ]
  },
  "NS137": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      8.9
    ]
  },
  "NS142": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      10.5
    ]
  },
  "NS143": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      11.5
    ]
  },
  "NS144": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      12.9
    ]
  },
  "NS145": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      14.1
    ]
  },
  "NS146": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      15.8
    ]
  },
  "NS147": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      17.3
    ]
  },
  "NS148": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      18.9
    ]
  },
  "KP2": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Greater Noida section"
    ],
    "distFromLineStartKm": [
      21.4
    ]
  },
  "PC": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      22.5
    ]
  },
  "A1N": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      23.4
    ]
  },
  "D1N": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      24.9
    ]
  },
  "GNO": {
    "opened": "25-01-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      26.2
    ]
  },
  "SJM": {
    "opened": "23-02-2011",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.9
    ]
  },
  "DKN": {
    "opened": "15-08-2011",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [
      "Pink Line"
    ],
    "notes": [
      "Highest point at 23.6m above ground"
    ],
    "distFromLineStartKm": [
      8.3
    ]
  },
  "DAC": {
    "opened": "15-08-2011",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [
      "Also known as NH-8"
    ],
    "distFromLineStartKm": [
      14.5
    ]
  },
  "IGA": {
    "opened": "23-02-2011",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "IGI Terminal 2 & 3; check-in at station"
    ],
    "distFromLineStartKm": [
      17.9
    ]
  },
  "YDS": {
    "opened": "17-09-2023",
    "layout": "Underground",
    "platformType": "Island",
    "interchangeLines": [],
    "notes": [
      "Former: IICC Dwarka Sec 25"
    ],
    "distFromLineStartKm": [
      23.1
    ]
  },
  "NLG": {
    "opened": "04-10-2019",
    "layout": "Elevated",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      1.5
    ]
  },
  "NJF": {
    "opened": "04-10-2019",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      3.9
    ]
  },
  "DHB": {
    "opened": "18-09-2021",
    "layout": "Underground",
    "platformType": "Side",
    "interchangeLines": [],
    "notes": [],
    "distFromLineStartKm": [
      5.7
    ]
  }
};
